<#
.SYNOPSIS
    Deploys Azure AI Vision (Computer Vision) resource for the License Plate Reader project.

.DESCRIPTION
    This script creates:
    1. A Resource Group (if it doesn't exist)
    2. An Azure AI Vision (Computer Vision) resource
    3. Outputs the configuration to a file and updates .env

.PREREQUISITES
    - Azure CLI installed and logged in (run: az login)
    - Sufficient permissions to create resources in the subscription

.USAGE
    .\deploy-azure-ai-vision.ps1

.NOTES
    Author: Generated by GitHub Copilot
    Date: January 2026
#>

# =============================================================================
# CONFIGURATION - Modify these values as needed
# =============================================================================

# Resource naming (change these to your preferred names)
$resourceGroupName = "rg-plate-reader"
$location = "swedencentral"                     # Azure region (use: az account list-locations -o table)
$visionResourceName = "vision-plate-reader-$((Get-Random -Maximum 9999))"  # Must be globally unique

# Output file for environment variables
$outputFile = Join-Path $PSScriptRoot "azure-vision-config.env"

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

function Write-Step {
    param([string]$Message)
    Write-Host "`n$('=' * 60)" -ForegroundColor Cyan
    Write-Host $Message -ForegroundColor Cyan
    Write-Host "$('=' * 60)" -ForegroundColor Cyan
}

function Write-Success {
    param([string]$Message)
    Write-Host (Get-Date)"- [SUCCESS] $Message" -ForegroundColor Green
}

function Write-Info {
    param([string]$Message)
    Write-Host (Get-Date)"- [INFO] $Message" -ForegroundColor Yellow
}

function Write-ErrorMessage {
    param([string]$Message)
    Write-Host (Get-Date)"- [ERROR] $Message" -ForegroundColor Red
}

# =============================================================================
# MAIN SCRIPT
# =============================================================================

Write-Host @"

╔══════════════════════════════════════════════════════════════╗
║     Azure AI Vision Deployment Script                        ║
║     License Plate Reader Project (OCR with Bounding Boxes)   ║
╚══════════════════════════════════════════════════════════════╝

"@ -ForegroundColor Magenta

# -----------------------------------------------------------------------------
# Step 1: Verify Azure CLI is installed and logged in
# -----------------------------------------------------------------------------
Write-Step "Step 1: Verifying Azure CLI"

try {
    $azVersion = az version --output json 2>$null | ConvertFrom-Json
    Write-Success "Azure CLI version: $($azVersion.'azure-cli')"
}
catch {
    Write-ErrorMessage "Azure CLI is not installed or not in PATH."
    Write-Host "Please install Azure CLI: https://docs.microsoft.com/cli/azure/install-azure-cli"
    exit 1
}

# Check if logged in
$account = az account show --output json 2>$null | ConvertFrom-Json
if (-not $account) {
    Write-Info "Not logged in to Azure. Running 'az login'..."
    az login
    $account = az account show --output json | ConvertFrom-Json
}

Write-Success "Logged in as: $($account.user.name)"
Write-Success "Subscription: $($account.name) ($($account.id))"

# -----------------------------------------------------------------------------
# Step 2: Create Resource Group
# -----------------------------------------------------------------------------
Write-Step "Step 2: Creating Resource Group"

$rgExists = az group exists --name $resourceGroupName 2>$null
if ($rgExists -eq "true") {
    Write-Info "Resource group '$resourceGroupName' already exists."
}
else {
    Write-Info "Creating resource group '$resourceGroupName' in '$location'..."
    az group create `
        --name $resourceGroupName `
        --location $location `
        --output none
    
    if ($LASTEXITCODE -eq 0) {
        Write-Success "Resource group created successfully."
    }
    else {
        Write-ErrorMessage "Failed to create resource group."
        exit 1
    }
}

# -----------------------------------------------------------------------------
# Step 3: Create Azure AI Vision (Computer Vision) Resource
# -----------------------------------------------------------------------------
Write-Step "Step 3: Creating Azure AI Vision Resource"

Write-Info "Creating Computer Vision resource '$visionResourceName'..."
Write-Info "This may take a few minutes..."

# Check if resource already exists
$existingResource = az cognitiveservices account show `
    --name $visionResourceName `
    --resource-group $resourceGroupName `
    --output json 2>$null | ConvertFrom-Json

if ($existingResource) {
    Write-Info "Vision resource '$visionResourceName' already exists."
}
else {
    az cognitiveservices account create `
        --name $visionResourceName `
        --resource-group $resourceGroupName `
        --location $location `
        --kind "ComputerVision" `
        --sku "S1" `
        --output none

    if ($LASTEXITCODE -eq 0) {
        Write-Success "AI Vision resource created successfully."
    }
    else {
        Write-ErrorMessage "Failed to create AI Vision resource."
        Write-Host "Note: The name must be globally unique. Try running the script again for a new random name."
        exit 1
    }
}

# -----------------------------------------------------------------------------
# Step 4: Retrieve Endpoint and API Key
# -----------------------------------------------------------------------------
Write-Step "Step 4: Retrieving Configuration"

# Get endpoint
$endpoint = az cognitiveservices account show `
    --name $visionResourceName `
    --resource-group $resourceGroupName `
    --query "properties.endpoint" `
    --output tsv

# Get API key
$apiKey = az cognitiveservices account keys list `
    --name $visionResourceName `
    --resource-group $resourceGroupName `
    --query "key1" `
    --output tsv

if (-not $endpoint -or -not $apiKey) {
    Write-ErrorMessage "Failed to retrieve endpoint or API key."
    exit 1
}

Write-Success "Configuration retrieved successfully."
Write-Info "Endpoint: $endpoint"

# -----------------------------------------------------------------------------
# Step 5: Write Configuration to File
# -----------------------------------------------------------------------------
Write-Step "Step 5: Writing Configuration to File"

# Create the configuration content
$configContent = @"
# =============================================================================
# Azure AI Vision Configuration
# Generated by deploy-azure-ai-vision.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
# =============================================================================

# Azure AI Vision (for plate_reader_vision.py)
AZURE_VISION_ENDPOINT=$endpoint
AZURE_VISION_API_KEY=$apiKey

# =============================================================================
# Resource Information (for reference)
# =============================================================================
# Resource Group: $resourceGroupName
# Vision Resource Name: $visionResourceName
# Location: $location
# SKU: S1 (Standard)
"@

# Write to file
$configContent | Out-File -FilePath $outputFile -Encoding UTF8

Write-Success "Configuration written to: $outputFile"

# -----------------------------------------------------------------------------
# Step 6: Update .env File
# -----------------------------------------------------------------------------
Write-Step "Step 6: Updating .env File"

$envFile = Join-Path $PSScriptRoot ".env"

if (Test-Path $envFile) {
    # Read existing .env content
    $envContent = Get-Content $envFile -Raw
    
    # Check if variables already exist and update them, or add them
    if ($envContent -match "AZURE_VISION_ENDPOINT=") {
        $envContent = $envContent -replace "AZURE_VISION_ENDPOINT=.*", "AZURE_VISION_ENDPOINT=$endpoint"
        Write-Info "Updated existing AZURE_VISION_ENDPOINT"
    }
    else {
        # Variable doesn't exist, will be handled below
        Write-Info "AZURE_VISION_ENDPOINT not found, will add it"
    }
    
    if ($envContent -match "AZURE_VISION_API_KEY=") {
        $envContent = $envContent -replace "AZURE_VISION_API_KEY=.*", "AZURE_VISION_API_KEY=$apiKey"
        Write-Info "Updated existing AZURE_VISION_API_KEY"
    }
    else {
        Write-Info "AZURE_VISION_API_KEY not found, will add it"
    }
    
    # If the variables contain placeholders, update them
    $envContent = $envContent -replace "AZURE_VISION_ENDPOINT=https://<your-resource>\.cognitiveservices\.azure\.com/", "AZURE_VISION_ENDPOINT=$endpoint"
    $envContent = $envContent -replace "AZURE_VISION_API_KEY=<your-api-key>", "AZURE_VISION_API_KEY=$apiKey"
    
    # Write back to file
    $envContent | Out-File -FilePath $envFile -Encoding UTF8 -NoNewline
    
    Write-Success ".env file updated successfully!"
}
else {
    Write-Info ".env file not found. Creating new .env file..."
    
    $newEnvContent = @"
# Azure AI Vision Configuration
AZURE_VISION_ENDPOINT=$endpoint
AZURE_VISION_API_KEY=$apiKey
"@
    
    $newEnvContent | Out-File -FilePath $envFile -Encoding UTF8
    Write-Success ".env file created successfully!"
}

# -----------------------------------------------------------------------------
# Step 7: Display Summary
# -----------------------------------------------------------------------------
Write-Step "Deployment Complete!"

Write-Host @"

╔══════════════════════════════════════════════════════════════╗
║                    DEPLOYMENT SUMMARY                        ║
╚══════════════════════════════════════════════════════════════╝

Resource Group:        $resourceGroupName
Vision Resource Name:  $visionResourceName
Location:              $location
SKU:                   S1 (Standard)

"@ -ForegroundColor Green

Write-Host "Configuration for .env file:" -ForegroundColor Yellow
Write-Host "─────────────────────────────────────────────────────────────"
Write-Host "AZURE_VISION_ENDPOINT=$endpoint" -ForegroundColor White
Write-Host "AZURE_VISION_API_KEY=$apiKey" -ForegroundColor White
Write-Host "─────────────────────────────────────────────────────────────"

Write-Host "`nConfiguration saved to: " -NoNewline
Write-Host $outputFile -ForegroundColor Cyan

Write-Host "`n.env file updated at: " -NoNewline
Write-Host $envFile -ForegroundColor Cyan

Write-Host @"

NEXT STEPS:
1. Your .env file has been updated with the Vision credentials
2. Test with: python plate_reader_vision.py
3. Annotated images will be saved to the 'output' folder

TROUBLESHOOTING COMMANDS:
# Verify the resource
az cognitiveservices account show --name "$visionResourceName" --resource-group "$resourceGroupName" --output table

# List keys
az cognitiveservices account keys list --name "$visionResourceName" --resource-group "$resourceGroupName" --output json

# Test endpoint (PowerShell)
Invoke-RestMethod -Uri "$($endpoint)vision/v3.2/read/analyze" -Method Post -Headers @{"Ocp-Apim-Subscription-Key"="$apiKey"}

"@ -ForegroundColor Yellow

Write-Host "`nScript completed successfully!" -ForegroundColor Green
