<#
.SYNOPSIS
    Deploys Azure AI Foundry resources and GPT-4o model for the License Plate Reader project.

.DESCRIPTION
    This script creates:
    1. A Resource Group (if it doesn't exist)
    2. An Azure AI Services account (AI Foundry)
    3. Deploys the GPT-4o model
    4. Outputs the configuration to a file for .env

.PREREQUISITES
    - Azure CLI installed and logged in (run: az login)
    - Sufficient permissions to create resources in the subscription

.USAGE
    .\deploy-azure-ai-foundry.ps1

.NOTES
    Author: Generated by GitHub Copilot
    Date: January 2026
#>

# =============================================================================
# CONFIGURATION - Modify these values as needed
# =============================================================================

# Resource naming (change these to your preferred names)
$resourceGroupName = "rg-plate-reader"
$location = "swedencentral"                    # Azure region (use: az account list-locations -o table)
$aiServicesName = "ai-plate-reader-$((Get-Random -Maximum 9999))"  # Must be globally unique
$deploymentName = "gpt-4o"                     # Model deployment name
$modelName = "gpt-4o"                          # Model to deploy
$modelVersion = "2024-11-20"                   # GPT-4o model version
$skuName = "GlobalStandard"                    # SKU for the deployment
$skuCapacity = 10                              # Tokens per minute (in thousands)

# Output file for environment variables
$outputFile = Join-Path $PSScriptRoot "azure-ai-config.env"

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

function Write-Step {
    param([string]$Message)
    Write-Host "`n$('=' * 60)" -ForegroundColor Cyan
    Write-Host $Message -ForegroundColor Cyan
    Write-Host "$('=' * 60)" -ForegroundColor Cyan
}

function Write-Success {
    param([string]$Message)
    Write-Host "[SUCCESS] $Message" -ForegroundColor Green
}

function Write-Info {
    param([string]$Message)
    Write-Host "[INFO] $Message" -ForegroundColor Yellow
}

function Write-ErrorMessage {
    param([string]$Message)
    Write-Host "[ERROR] $Message" -ForegroundColor Red
}

# =============================================================================
# MAIN SCRIPT
# =============================================================================

Write-Host @"

╔══════════════════════════════════════════════════════════════╗
║     Azure AI Foundry Deployment Script                       ║
║     License Plate Reader Project                             ║
╚══════════════════════════════════════════════════════════════╝

"@ -ForegroundColor Magenta

# -----------------------------------------------------------------------------
# Step 1: Verify Azure CLI is installed and logged in
# -----------------------------------------------------------------------------
Write-Step "Step 1: Verifying Azure CLI"

try {
    $azVersion = az version --output json 2>$null | ConvertFrom-Json
    Write-Success "Azure CLI version: $($azVersion.'azure-cli')"
}
catch {
    Write-ErrorMessage "Azure CLI is not installed or not in PATH."
    Write-Host "Please install Azure CLI: https://docs.microsoft.com/cli/azure/install-azure-cli"
    exit 1
}

# Check if logged in
$account = az account show --output json 2>$null | ConvertFrom-Json
if (-not $account) {
    Write-Info "Not logged in to Azure. Running 'az login'..."
    az login
    $account = az account show --output json | ConvertFrom-Json
}

Write-Success "Logged in as: $($account.user.name)"
Write-Success "Subscription: $($account.name) ($($account.id))"

# -----------------------------------------------------------------------------
# Step 2: Create Resource Group
# -----------------------------------------------------------------------------
Write-Step "Step 2: Creating Resource Group"

$rgExists = az group exists --name $resourceGroupName 2>$null
if ($rgExists -eq "true") {
    Write-Info "Resource group '$resourceGroupName' already exists."
}
else {
    Write-Info "Creating resource group '$resourceGroupName' in '$location'..."
    az group create `
        --name $resourceGroupName `
        --location $location `
        --output none
    
    if ($LASTEXITCODE -eq 0) {
        Write-Success "Resource group created successfully."
    }
    else {
        Write-ErrorMessage "Failed to create resource group."
        exit 1
    }
}

# -----------------------------------------------------------------------------
# Step 3: Create Azure AI Services Account
# -----------------------------------------------------------------------------
Write-Step "Step 3: Creating Azure AI Services Account"

Write-Info "Creating AI Services account '$aiServicesName'..."
Write-Info "This may take a few minutes..."

az cognitiveservices account create `
    --name $aiServicesName `
    --resource-group $resourceGroupName `
    --location $location `
    --kind "AIServices" `
    --sku "S0" `
    --custom-domain $aiServicesName `
    --output none

if ($LASTEXITCODE -eq 0) {
    Write-Success "AI Services account created successfully."
}
else {
    Write-ErrorMessage "Failed to create AI Services account."
    Write-Host "Note: The name must be globally unique. Try running the script again for a new random name."
    exit 1
}

# -----------------------------------------------------------------------------
# Step 4: Deploy GPT-4o Model
# -----------------------------------------------------------------------------
Write-Step "Step 4: Deploying GPT-4o Model"

Write-Info "Deploying model '$modelName' as '$deploymentName'..."
Write-Info "SKU: $skuName, Capacity: ${skuCapacity}K TPM"

az cognitiveservices account deployment create `
    --name $aiServicesName `
    --resource-group $resourceGroupName `
    --deployment-name $deploymentName `
    --model-name $modelName `
    --model-version $modelVersion `
    --model-format "OpenAI" `
    --sku-name $skuName `
    --sku-capacity $skuCapacity `
    --output none

if ($LASTEXITCODE -eq 0) {
    Write-Success "GPT-4o model deployed successfully."
}
else {
    Write-ErrorMessage "Failed to deploy GPT-4o model."
    Write-Host "This could be due to:"
    Write-Host "  - Model not available in the selected region"
    Write-Host "  - Quota limits exceeded"
    Write-Host "  - Model version not available"
    Write-Host "`nTry a different region or check your quota."
    exit 1
}

# -----------------------------------------------------------------------------
# Step 5: Retrieve Endpoint and API Key
# -----------------------------------------------------------------------------
Write-Step "Step 5: Retrieving Configuration"

# Get endpoint
$endpoint = az cognitiveservices account show `
    --name $aiServicesName `
    --resource-group $resourceGroupName `
    --query "properties.endpoint" `
    --output tsv

# Get API key
$apiKey = az cognitiveservices account keys list `
    --name $aiServicesName `
    --resource-group $resourceGroupName `
    --query "key1" `
    --output tsv

if (-not $endpoint -or -not $apiKey) {
    Write-ErrorMessage "Failed to retrieve endpoint or API key."
    exit 1
}

Write-Success "Configuration retrieved successfully."

# -----------------------------------------------------------------------------
# Step 6: Write Configuration to File
# -----------------------------------------------------------------------------
Write-Step "Step 6: Writing Configuration to File"

# Construct the models endpoint (for Azure AI Inference SDK)
$modelsEndpoint = "$($endpoint)models"

# Create the configuration content
$configContent = @"
# =============================================================================
# Azure AI Foundry Configuration
# Generated by deploy-azure-ai-foundry.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
# =============================================================================

# Azure AI Foundry (for plate_reader.py)
# Use this endpoint format for the Azure AI Inference SDK
AZURE_AI_ENDPOINT=$modelsEndpoint
AZURE_AI_API_KEY=$apiKey
AZURE_AI_MODEL=$deploymentName

# =============================================================================
# Resource Information (for reference)
# =============================================================================
# Resource Group: $resourceGroupName
# AI Services Name: $aiServicesName
# Location: $location
# Model: $modelName (version: $modelVersion)
# Deployment Name: $deploymentName
# SKU: $skuName (Capacity: ${skuCapacity}K TPM)
"@

# Write to file
$configContent | Out-File -FilePath $outputFile -Encoding UTF8

Write-Success "Configuration written to: $outputFile"

# -----------------------------------------------------------------------------
# Step 7: Display Summary
# -----------------------------------------------------------------------------
Write-Step "Deployment Complete!"

Write-Host @"

╔══════════════════════════════════════════════════════════════╗
║                    DEPLOYMENT SUMMARY                        ║
╚══════════════════════════════════════════════════════════════╝

Resource Group:     $resourceGroupName
AI Services Name:   $aiServicesName
Location:           $location
Model Deployed:     $modelName ($modelVersion)
Deployment Name:    $deploymentName

"@ -ForegroundColor Green

Write-Host "Configuration for .env file:" -ForegroundColor Yellow
Write-Host "─────────────────────────────────────────────────────────────"
Write-Host "AZURE_AI_ENDPOINT=$modelsEndpoint" -ForegroundColor White
Write-Host "AZURE_AI_API_KEY=$apiKey" -ForegroundColor White
Write-Host "AZURE_AI_MODEL=$deploymentName" -ForegroundColor White
Write-Host "─────────────────────────────────────────────────────────────"

Write-Host "`nConfiguration saved to: " -NoNewline
Write-Host $outputFile -ForegroundColor Cyan

Write-Host @"

NEXT STEPS:
1. Copy the values above to your .env file, or
2. Run: Copy-Item "$outputFile" ".env" (then merge with existing .env)
3. Test with: python plate_reader.py

"@ -ForegroundColor Yellow

# -----------------------------------------------------------------------------
# Optional: Offer to update .env directly
# -----------------------------------------------------------------------------
$envFile = Join-Path $PSScriptRoot ".env"
if (Test-Path $envFile) {
    Write-Host "Would you like to update your .env file automatically? (y/n): " -NoNewline -ForegroundColor Cyan
    $response = Read-Host
    
    if ($response -eq "y" -or $response -eq "Y") {
        # Read existing .env
        $envContent = Get-Content $envFile -Raw
        
        # Update or add the Azure AI Foundry variables
        $envContent = $envContent -replace 'AZURE_AI_ENDPOINT=.*', "AZURE_AI_ENDPOINT=$modelsEndpoint"
        $envContent = $envContent -replace 'AZURE_AI_API_KEY=.*', "AZURE_AI_API_KEY=$apiKey"
        $envContent = $envContent -replace 'AZURE_AI_MODEL=.*', "AZURE_AI_MODEL=$deploymentName"
        
        $envContent | Out-File -FilePath $envFile -Encoding UTF8 -NoNewline
        Write-Success ".env file updated successfully!"
    }
}

Write-Host "`nScript completed successfully!" -ForegroundColor Green
